-- Star Syndicate member-community MVP. All public tables use RLS and explicit Data API grants.
create extension if not exists pgcrypto;

-- Project-created helper is for DDL automation only; never expose it over RPC.
do $$ begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end $$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  bio text check (char_length(bio) <= 600), location text check (char_length(location) <= 120),
  avatar_path text, favorite_memory text check (char_length(favorite_memory) <= 500),
  is_public boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.interests (id bigint generated by default as identity primary key, slug text unique not null, name text unique not null, category text not null default 'mystical');
create table public.profile_interests (profile_id uuid references public.profiles(id) on delete cascade, interest_id bigint references public.interests(id) on delete cascade, created_at timestamptz not null default now(), primary key(profile_id, interest_id));
create table public.events (id uuid primary key default gen_random_uuid(), title text not null check (char_length(title) between 1 and 160), description text, starts_at timestamptz not null, ends_at timestamptz, location text, cover_path text, is_published boolean not null default false, created_at timestamptz not null default now(), check (ends_at is null or ends_at >= starts_at));
create table public.memories (id uuid primary key default gen_random_uuid(), author_id uuid not null constraint memories_author_id_fkey references public.profiles(id) on delete cascade, event_id uuid references public.events(id) on delete set null, caption text check (char_length(caption) <= 1000), image_path text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reactions (memory_id uuid references public.memories(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, kind text not null default 'star' check (kind = 'star'), created_at timestamptz not null default now(), primary key(memory_id,user_id));
create table public.comments (id uuid primary key default gen_random_uuid(), memory_id uuid not null references public.memories(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, body text not null check (char_length(body) between 1 and 1000), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index memories_created_at_idx on public.memories(created_at desc); create index memories_author_idx on public.memories(author_id); create index memories_event_idx on public.memories(event_id); create index comments_memory_idx on public.comments(memory_id, created_at); create index comments_author_idx on public.comments(author_id); create index reactions_memory_idx on public.reactions(memory_id); create index reactions_user_idx on public.reactions(user_id); create index profile_interests_interest_idx on public.profile_interests(interest_id);

create function public.set_updated_at() returns trigger language plpgsql set search_path = '' as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
create trigger memories_updated before update on public.memories for each row execute function public.set_updated_at();
create trigger comments_updated before update on public.comments for each row execute function public.set_updated_at();
revoke execute on function public.set_updated_at() from public, anon, authenticated;

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin insert into public.profiles(id,display_name) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(coalesce(new.email,'member'),'@',1))); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
revoke execute on function public.handle_new_user() from public, anon, authenticated;

alter table public.profiles enable row level security; alter table public.interests enable row level security; alter table public.profile_interests enable row level security; alter table public.events enable row level security; alter table public.memories enable row level security; alter table public.reactions enable row level security; alter table public.comments enable row level security;
create policy "public profiles readable" on public.profiles for select to anon,authenticated using (is_public or id=(select auth.uid()));
create policy "members update own profile" on public.profiles for update to authenticated using (id=(select auth.uid())) with check (id=(select auth.uid()));
create policy "interests readable" on public.interests for select to anon,authenticated using (true);
create policy "profile interests readable" on public.profile_interests for select to anon,authenticated using (exists(select 1 from public.profiles p where p.id=profile_id and (p.is_public or p.id=(select auth.uid()))));
create policy "members add own interests" on public.profile_interests for insert to authenticated with check (profile_id=(select auth.uid()));
create policy "members remove own interests" on public.profile_interests for delete to authenticated using (profile_id=(select auth.uid()));
create policy "published events readable" on public.events for select to anon,authenticated using (is_published);
create policy "public memories readable" on public.memories for select to anon,authenticated using (exists(select 1 from public.profiles p where p.id=author_id and p.is_public));
create policy "members create own memories" on public.memories for insert to authenticated with check (author_id=(select auth.uid()) and split_part(image_path,'/',1)=(select auth.uid())::text);
create policy "members update own memories" on public.memories for update to authenticated using (author_id=(select auth.uid())) with check (author_id=(select auth.uid()));
create policy "members delete own memories" on public.memories for delete to authenticated using (author_id=(select auth.uid()));
create policy "reactions readable" on public.reactions for select to anon,authenticated using (true);
create policy "members add own reactions" on public.reactions for insert to authenticated with check (user_id=(select auth.uid()));
create policy "members remove own reactions" on public.reactions for delete to authenticated using (user_id=(select auth.uid()));
create policy "comments readable" on public.comments for select to anon,authenticated using (true);
create policy "members add own comments" on public.comments for insert to authenticated with check (author_id=(select auth.uid()));
create policy "members update own comments" on public.comments for update to authenticated using (author_id=(select auth.uid())) with check (author_id=(select auth.uid()));
create policy "members delete own comments" on public.comments for delete to authenticated using (author_id=(select auth.uid()));

grant usage on schema public to anon,authenticated; grant select on public.profiles,public.interests,public.profile_interests,public.events,public.memories,public.reactions,public.comments to anon,authenticated; grant update on public.profiles to authenticated; grant insert,delete on public.profile_interests to authenticated; grant insert,update,delete on public.memories to authenticated; grant insert,delete on public.reactions to authenticated; grant insert,update,delete on public.comments to authenticated; grant usage,select on all sequences in schema public to authenticated;

insert into public.interests(slug,name,category) values ('tarot','Tarot','divination'),('reiki','Reiki','energy'),('yoga','Yoga','movement'),('meditation','Meditation','mindfulness'),('astrology','Astrology','divination'),('sound-healing','Sound Healing','energy'),('breathwork','Breathwork','mindfulness'),('herbalism','Herbalism','earth'),('crystals','Crystals','earth'),('dance','Dance','creative'),('djing','DJing','creative'),('photography','Photography','creative'),('visual-art','Visual Art','creative');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('avatars','avatars',true,2097152,array['image/jpeg','image/png','image/webp']),('memories','memories',true,8388608,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "member image uploads" on storage.objects for insert to authenticated with check (bucket_id in ('avatars','memories') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "member image updates" on storage.objects for update to authenticated using (bucket_id in ('avatars','memories') and owner_id=(select auth.uid())::text) with check ((storage.foldername(name))[1]=(select auth.uid())::text);
create policy "member image deletes" on storage.objects for delete to authenticated using (bucket_id in ('avatars','memories') and owner_id=(select auth.uid())::text);

